### ISSUE TITLE
failed to open file before-1.wav

### ISSUE THREAD

**Issue by bagustris** [ssj71/octaveIRplots#1]
Hey, would you like to provide the wav files so the demo can be run? And why there are three wav files to plot IR? is that one sound file enough to compute IR?

**Comment by ssj71** [comment]
these functions work on an IR file already measured or computed. You can download a lot of them at places like http://www.resoundsound.com/4-impulse-response-reverb-packs/
or you can record your own using tools like aliki (http://kokkinizita.linuxaudio.org/linuxaudio/)

the plotMyIRs.m script is just an example of using the functions with some IRs I measured, but you have a good point, I've now added that file. Please try again.
